### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by Jbarget**
adds:
- skeleton server (after running `mix phoenix.new`)
- adds `travis.yml`

### CODE REVIEW

**Comment by nelsonic** [comment]
Guys I ❤️  your enthusiasm! 🎉 
_however_ the whole point of version control is that we can create a completely new version of the app in the _existing_ repository ... 
Please simply push this `initial-setup` branch to the _existing_ git remote: `git@github.com:dwyl/tudo.git`

also the _first_ part of the mini project is writing a _script_ to download all issues from all repos in an organisation or user as discussed in: https://github.com/dwyl/tudo/issues/146#issuecomment-285312419
the script already has a repo: https://github.com/dwyl/github-backup

**Comment by des-des** [comment]
@nelsonic Thanks for catching this quickly!

We were following what was done for the skills-wheel project. Will push somewhere and fix issue numbers in commit messages.

Sorry, we misunderstood you in that comment.

Do you want us to publish a hex module for this first part? Need to do some more research plus scope out some more setup time.

We have some options here.
 1. Build a script that takes an api token + org name and returns all the issues to caller.
 2. Build a script that does the above and saves to fs. Then, copy / repush that project to tudo and modify it to meet the needs of this project.

**Comment by des-des** [comment]
@nelsonic 
  1. Not sure exactly how we will share code between this project and gh-backup.
  2. Still not sure about the scope for gh-backup (ux, etc).

So we are not sitting on our hands while working out the answers to these questions, would it be possible to continue with this project for now?
I am sure we can easily transpose what we have learned / built here into gh-backup without much hassle once we know what it requires..

**Comment by nelsonic** [comment]
@des-des raise questions about https://github.com/dwyl/github-backup 
in https://github.com/dwyl/github-backup/issues so others know where to look.

I apologise if something is unclear but a PR is not the place to clarify it 
(_just so we can keep track of questions/answers in a logical way..._)

**Comment by Jbarget** [comment]
closing as all has moved to https://github.com/dwyl/tudo

**Comment by nelsonic** [comment]
thanks JB! 👍

**Pull request closed without merging**
